### PR TITLE
Fixing Broken Tests

### PR DESCRIPTION
**Pull request by aparsons**
I discovered six different broken tests. The following changes should cause all the tests to now pass.

Please review to ensure this was done properly.

### CODE REVIEW

**Comment by aparsons** [comment]
I accept the contributor terms specified at https://github.com/thymeleaf/thymeleaf-dist/blob/master/CONTRIBUTING.markdown

**Comment by jmiguelsamper** [comment]
Hi,

Thanks for your report.

Could you confirm with JVM version and system locale you're using to run the tests?

Unfortunately, date formatting has been changing on every version of Java so we cannot keep tests working for all versions. Currently the tests work for the latest OpenJDK 11 as Thymeleaf core also updated to 11.

That does not mean that binaries are not compatible with previous Java versions, as they're generated for Java 8 compatibility.

**Comment by aparsons** [comment]
@jmiguelsamper I was using Java 8 with a system locale of en_US. I will try it on OpenJDK 11 and open a new PR if the tests are still broken. Thanks!

**Comment by aparsons** [comment]
@jmiguelsamper You were correct. All of the tests passed _except for one_ by using OpenJDK 11.0.1.

The test method [testFormatStandardPattern()](https://github.com/thymeleaf/thymeleaf-extras-java8time/blob/3.0-master/src/test/java/org/thymeleaf/extras/java8time/expression/TemporalsFormattingTest.java#L62) was still broken. I also can confirm my default locale is en_US.

**Comment by jmiguelsamper** [comment]
Oh, sorry, I made two mistakes here.

First, I used Locale.ENGLISH in the tests. Locale.ENGLISH does not include a country variant so my test results worked for en_UK but not for en_US. I've switched to Locale.US (en_US) in all tests.

On the other hand, I did not used the localised versions of the hardcoded patterns from java.time.format.FormatStyle (SHORT, MEDIUM, LONG, FULL).

Both issues are fixed in 3.0.4-SNAPSHOT.

**Comment by aparsons** [comment]
@jmiguelsamper Awesome!

**Pull request closed without merging**
