### PR TITLE
Added formatting temporals with patterns in different time zone

### PR DESCRIPTION
**Pull request by dheid**
Hi @danielfernandez !

I added a possibilty to format temporals using a different timezone than the given one.

I also updated the project's dependencies and removed log4j in test scope (it's not needed anyway, but let's not use such an old log4j version, just use slf4j-simple and everything is fine).

Would be great if you could include this.

Best regards

Daniel

### CODE REVIEW

**Comment by jmiguelsamper** [comment]
Hello Daniel,

Thanks for your proposal.

I will see if I can merge this but please take a look first at the contributing terms at https://github.com/thymeleaf/thymeleaf-dist/blob/main/CONTRIBUTING.markdown

If you accept the terms you can simply state it on a comment here.

Thanks!

**Comment by dheid** [comment]
Hi @jmiguelsamper! I accept the terms. 🙂

**Comment by dheid** [comment]
@jmiguelsamper Ping? 😶

**Comment by dheid** [comment]
@jmiguelsamper Hi! Are you there?

**Comment by dheid** [comment]
😢

**Comment by dheid** [comment]
@jmiguelsamper Did I misunderstand something?

**Comment by danielfernandez** [comment]
Hello @dheid. Sorry for the lack of response. This repository is in the process of being deprecated for 3.1 as a part of a global re-organization of the whole project structure (`thymeleaf-extras-java8time` will be included into the Thymeleaf core), and I was somehow filtering out the repo's notifications.

Please allow me some days to have a look at your contribution. Thanks.

**Comment by danielfernandez** [comment]
This has been merged, and will port it right away into 3.1 as a part of the integration of `thymeleaf-extras-java8time` into thymeleaf's core.

**Comment by danielfernandez** [comment]
Thanks so much @dheid

**Pull request merged**
