### PR TITLE
Expression dialect adapted to Thymeleaf 3.X structure.

### PR DESCRIPTION
**Pull request by imartinezortiz**
Upgrades the project to thymeleaf 3.X.

### CODE REVIEW

**Comment by danielfernandez** [comment]
@jmiguelsamper looks quite good to me, what do you think? it would have to be merged to a `3.0-dev` branch though...

**Comment by danielfernandez** [comment]
@imartinezortiz thanks a lot, by the way :-) One thing: in order to accept your contribution, we'd need you to carefully read https://github.com/thymeleaf/thymeleaf-extras-java8time/blob/dcd8a6a0025bb59b58158fd160ebc64a30cf9b82/CONTRIBUTING.markdown and explicitly state your agreement with what is said there (a comment here will suffice).

**Comment by imartinezortiz** [comment]
I agree / accept the Thymeleaf CLA.

**Comment by imartinezortiz** [comment]
BTW, if you finally create a new branch for 3.0-dev, let me know and I'll send you a new PR.

**Comment by jmiguelsamper** [comment]
Thanks for your work, it's been merged to 3.0-dev.

@imartinezortiz Would you like to be listed on the contributors page?

**Comment by jmiguelsamper** [comment]
@imartinezortiz if you want I can list you in the contributors section but I would need a personal email (not your job's) to show there.

**Comment by imartinezortiz** [comment]
Thank you, you can use imartinezortiz AT gmail DOT com.

**Comment by danielfernandez** [comment]
Site updated. Thanks Iván.

**Pull request closed without merging**
